Fix compilation on OS/2
off_t requires sys/types.h on OS/2

-----
    [CC] test/../ivfenc.c.o
In file included from test/.././ivfenc.h:13:0,
                 from test/../ivfenc.c:11:
test/../././tools_common.h:36:9: error: unknown type name 'off_t'
 typedef off_t FileOffset;
         ^~~~~
make.exe[1]: *** [test/../ivfenc.c.o] Error 1
-----

Change-Id: Ia09935e5de8573e63185369fc139e3355664afd1